### ISSUE TITLE
logi-in credentials not working for LDAP

### ISSUE THREAD

**Issue by adefemi171** [sheeeng/jenkins-configuration-as-code-workshop-prerequisites#1]
I tried logging in with the credentials provided for LDAP in the README.md but I keep getting invalid DN syntax for the user (Login failed)

  | Unable to connect to LDAP server slapd
Error: Invalid DN syntax (34) for user
  | Failed to Authenticate to server
Invalid Username or Password.

**Comment by sheeeng** [comment]
Hi Adefemi, could you confirm that you have used the following credentials?

Login phpLDAPadmin using the following credentials.
Login DN: `cn=admin,dc=acme,dc=local`
Password: `changeit`

**Comment by sheeeng** [comment]
What is your output of `docker-compose ps` after `make`? Here is my output.

```console
$ make
$ docker-compose ps
                     Name                                   Command               State                       Ports
---------------------------------------------------------------------------------------------------------------------------------------
jenkins-configuration-as-code-workshop-          /sbin/tini -- /usr/local/b ...   Up      0.0.0.0:50000->50000/tcp,
prerequisites_jenkins_1                                                                   0.0.0.0:8080->8080/tcp
jenkins-configuration-as-code-workshop-          sh -c ${SONATYPE_DIR}/star ...   Up      0.0.0.0:8081->8081/tcp
prerequisites_nexus_1
jenkins-configuration-as-code-workshop-          /container/tool/run              Up      443/tcp, 0.0.0.0:8090->80/tcp
prerequisites_phpldapadmin_1
jenkins-configuration-as-code-workshop-          slapd -h ldap:/// -g openl ...   Up      0.0.0.0:389->389/tcp, 0.0.0.0:636->636/tcp
prerequisites_slapd_1
```

I was able to login to [phpLDAPadmin](http://localhost:8090) using the following credentials.
Login DN: `cn=admin,dc=acme,dc=local`
Password: `changeit`

Please do not hesitate to contact me if you have further questions.

**Comment by adefemi171** [comment]
Hi thanks for the swift response and this was my output
                     Name                                   Command               State                       Ports                    
---------------------------------------------------------------------------------------------------------------------------------------
jenkins-configuration-as-code-workshop-          /sbin/tini -- /usr/local/b ...   Up      0.0.0.0:50000->50000/tcp,                    
prerequisites_jenkins_1                                                                   0.0.0.0:8080->8080/tcp                       
jenkins-configuration-as-code-workshop-          sh -c ${SONATYPE_DIR}/star ...   Up      0.0.0.0:8081->8081/tcp                       
prerequisites_nexus_1                                                                                                                  
jenkins-configuration-as-code-workshop-          /container/tool/run              Up      443/tcp, 0.0.0.0:8090->80/tcp                
prerequisites_phpldapadmin_1                                                                                                           
jenkins-configuration-as-code-workshop-          slapd -h ldap:/// -g openl ...   Up      0.0.0.0:389->389/tcp, 0.0.0.0:636->636/tcp   
prerequisites_slapd_1   

And yes I used `admin` as the username and `changeit` as the password

**Comment by sheeeng** [comment]
Hi Adefemi, thanks for the logs.

Could you try to use the entire `cn=admin,dc=acme,dc=local` string for the Login DN instead of using the one word of `admin`?

**Comment by sheeeng** [comment]
Hi Adefemi, thank you for the logs.

Could you try to use the entire `cn=admin,dc=acme,dc=local` string for the Login DN field?

We should not use the single `admin` word for Login DN.

**Comment by adefemi171** [comment]
Thanks, that worked.

**Comment by adefemi171** [comment]
-
